{"ts": 1757881575.4164095, "event": "job_started", "data": {}}
{"ts": 1757881575.4165843, "event": "info", "data": {"message": "qa_loop_start", "question": "Making AI Helpful for Everyone how ?"}}
{"ts": 1757881575.919985, "event": "error", "data": {"message": "qa_failed", "error": "Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************8XgA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}", "traceback": "Traceback (most recent call last):\n  File \"/workspaces/Pathway-Challenge/app/api/server.py\", line 108, in task\n    trace = qa.run(req.question)\n            ^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/Pathway-Challenge/app/services/qa_loop.py\", line 74, in run\n    reform_json = self._chat('reformulate', settings.json_response_system_prompt, f\"{REFORM_PROMPT}\\nQuery: {current_query}\", '{\"reformulated\":\"string\"}')\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/Pathway-Challenge/app/services/qa_loop.py\", line 45, in _chat\n    resp = self.emb.chat_json(system, prompt, schema)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/Pathway-Challenge/app/services/openai_client.py\", line 78, in chat_json\n    resp = self.client.chat.completions.create(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/openai/_utils/_utils.py\", line 286, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/openai/resources/chat/completions/completions.py\", line 1147, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/openai/_base_client.py\", line 1259, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/openai/_base_client.py\", line 1047, in request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************8XgA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}\n"}}
